/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;
import org.jooq.mcve.Mcve;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum TestEnum implements EnumType {

    foo_bar("foo-bar"),

    baz_qux("baz-qux");

    private final String literal;

    private TestEnum(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mcve.MCVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "test_enum";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
