CREATE TYPE test_enum AS ENUM('foo-bar', 'baz-qux');
-- actual enum has many more values

CREATE TABLE test (
  id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value  test_enum[] NOT NULL DEFAULT '{}'
);
