/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.jooq.mcve.tables.Test;


/**
 * A class modelling indexes of tables of the <code>mcve</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TEST_PKEY = Indexes0.TEST_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index TEST_PKEY = Internal.createIndex("test_pkey", Test.TEST, new OrderField[] { Test.TEST.ID }, true);
    }
}
