/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.mcve.tables.Test;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mcve extends SchemaImpl {

    private static final long serialVersionUID = -1474527465;

    /**
     * The reference instance of <code>mcve</code>
     */
    public static final Mcve MCVE = new Mcve();

    /**
     * The table <code>mcve.test</code>.
     */
    public final Test TEST = org.jooq.mcve.tables.Test.TEST;

    /**
     * No further instances allowed
     */
    private Mcve() {
        super("mcve", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Test.TEST);
    }
}
