/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve;


import org.jooq.mcve.tables.Test;


/**
 * Convenience access to all tables in mcve
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mcve.test</code>.
     */
    public static final Test TEST = org.jooq.mcve.tables.Test.TEST;
}
